// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgBW1TuAB0fSKE0s-10f4M-eFlmtjxiQo',
    appId: '1:1080584027846:web:399e809aaa6bce9113a1c7',
    messagingSenderId: '1080584027846',
    projectId: 'projectpember',
    authDomain: 'projectpember.firebaseapp.com',
    databaseURL: 'https://projectpember-default-rtdb.firebaseio.com',
    storageBucket: 'projectpember.firebasestorage.app',
    measurementId: 'G-6B0RPDZWMY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxNZgaRGsy_6oa-kbnR8JYHrbAm8fT9c8',
    appId: '1:1080584027846:android:d1d887aa189395da13a1c7',
    messagingSenderId: '1080584027846',
    projectId: 'projectpember',
    databaseURL: 'https://projectpember-default-rtdb.firebaseio.com',
    storageBucket: 'projectpember.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRDOfk4aXTh7KADEuqxxmgG0BMSvvEEfg',
    appId: '1:1080584027846:ios:2908f1f7097cef7013a1c7',
    messagingSenderId: '1080584027846',
    projectId: 'projectpember',
    databaseURL: 'https://projectpember-default-rtdb.firebaseio.com',
    storageBucket: 'projectpember.firebasestorage.app',
    iosBundleId: 'com.example.projectPember',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRDOfk4aXTh7KADEuqxxmgG0BMSvvEEfg',
    appId: '1:1080584027846:ios:2908f1f7097cef7013a1c7',
    messagingSenderId: '1080584027846',
    projectId: 'projectpember',
    databaseURL: 'https://projectpember-default-rtdb.firebaseio.com',
    storageBucket: 'projectpember.firebasestorage.app',
    iosBundleId: 'com.example.projectPember',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgBW1TuAB0fSKE0s-10f4M-eFlmtjxiQo',
    appId: '1:1080584027846:web:df1c43d29c0ccfb613a1c7',
    messagingSenderId: '1080584027846',
    projectId: 'projectpember',
    authDomain: 'projectpember.firebaseapp.com',
    databaseURL: 'https://projectpember-default-rtdb.firebaseio.com',
    storageBucket: 'projectpember.firebasestorage.app',
    measurementId: 'G-PWYLKZEBD9',
  );

}